### ISSUE TITLE
Cannot leave comments yet

### ISSUE THREAD

**Issue by lostfile** [zedsa/Lairs#1]
I install the  Extension on Firefox and I tried to leave a comment on something  I tried hitting the enter button or but nothing happened

**Comment by zedsa** [comment]
> I install the Extension on Firefox and I tried to leave a comment on something I tried hitting the enter button or but nothing happened

the extension has been updated. everything should be working.

**Comment by zedsa** [comment]
i'm going to close this issue since it has been fixed.
